### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by caseymhunt** [mjmlio/language-mjml#1]
I am not seeing syntax highlighting in Atom. I have tried multiple syntax themes and application themes, to no avail. White text throughout. 

Suggestions?

**Comment by WeshGuillaume** [comment]
Can you try to remove the package from ~/.atom/packages/ and reinstall it with `apm install language-mjml` ?

**Comment by caseymhunt** [comment]
That did the trick! 

For what it's worth, the syntax theme [Northem Dark Atom Syntax](https://atom.io/themes/northem-dark-atom-syntax) does not properly do synxtax highlighting for MJML files. The default themes seem to work however!

**Comment by arcticicestudio** [comment]
Syntax Highlighting languages are detected by the file extension / editor class scope, it's hard to support all of them, but also the theme is still in `indev` state ;)
Nevertheless, I released a new package version [`0.15.0`](https://github.com/arcticicestudio/northem-dark-atom-syntax/releases/tag/v0.15.0) which adds support for the [MJML](https://atom.io/packages/language-mjml) language package.
Is MJML 100% compatible to HTML or are there any differences or maybe additions I've to add?

By the way, MJML is a really awesome project, never headed about it, but but I will definitely take a look at it (used  the [Ceberus](http://tedgoas.github.io/Cerberus/) project for my email templates, maybe migrate them to MJML).

**Comment by WeshGuillaume** [comment]
Sorry for the delay guys!

You can use Html inside your mjml, mjml just add a few more tags to html ;)

**Comment by WeshGuillaume** [comment]
Thanks @arcticicestudio ! Thats awesome!
