### ISSUE TITLE
Some components display an error

### ISSUE THREAD

**Issue by elena-melentii** [mjmlio/language-mjml#10]
Some components like mj-image, mj-wrapper don't work.
It displays a parsing error.

**Comment by ngarnier** [comment]
hi @elena-melentii, indeed `mj-wrapper` is part of v3.3.0 which is in beta so the plugin hasn't been updated yet, but we'd greatly appreciate a contribution to udpate it 🤗 .

If you want to contribute and add the snippet, here's an example on how to do so: https://github.com/mjmlio/language-mjml/pull/7

**Comment by ngarnier** [comment]
Fixed in [v1.9.0](https://github.com/mjmlio/language-mjml/releases/tag/v1.9.0), thanks!
