### ISSUE TITLE
Element mj-include doesn't exist or is not registered

### ISSUE THREAD

**Issue by nicholas-c** [mjmlio/language-mjml#17]
https://mjml.io/documentation/#mj-include

It's an official element in MJML and renders fine (CLI doesn't give any errors) - However the linter in Atom flags this as a linting error.

Usage: `<mj-include path="./partials/_header" />`

**Comment by iRyusa** [comment]
Hi !
I think the linter has not yet been updated to MJML4 and you're on the wrong repo for this https://github.com/mjmlio/atom-linter-mjml so that's why it behave like that.

i'm closing this issue feel free to reopen on the proper repo

**Comment by nicholas-c** [comment]
Doh! My apologies! 🤦‍♂️
