### ISSUE TITLE
mjml-style tag

### ISSUE THREAD

**Issue by matteobertoldo** [mjmlio/language-mjml#18]
It's possible to update the same default style that is in the `<style>` tag also in this language? <br />
<img width="469" alt="style" src="https://user-images.githubusercontent.com/15775323/51836395-9fd4b400-2300-11e9-94d6-ae1d16d8cca9.png">

(For example the tag `<style>` that is in an `.html` file)

Thanks.

**Comment by kmcb777** [comment]
Hi @matteobertoldo, i'm not sure i understand what you want, if you use the `<mj-style>` tag without `inline` it will add the css in the head `<style>` tag, after the defaults so you can override them.

**Comment by kmcb777** [comment]
@matteobertoldo actually if what you want is some kind of snippet, you can add it directly in your atom snippets, something like this will do the job : 
```
'.text.mjml.basic, .text.mjml, .text.mjml .meta.scope.between-tag-pair, .text.mjml .punctuation.tag.begin':

  'Default style':
    'prefix': 'styledef'
    'body': """
      <mj-style inline="inline">
          a {
              color: #000;
              text-decoration: none;
          }
      </mj-style>
    """
```

**Comment by matteobertoldo** [comment]
Mmh I did not mean a snippet code, but the possibility of having the same "highlight" color, which I have for the css code in the `style` tag, as in the` .html` files. I investigated in the `mjml.cson` file in the` grammars` directory and added the necessary regex to support the `mj-style` tag: <br /> `'begin': '(?:^\\s+)?(<)((?i:mj-style))\\b(?![^>]*/>)'` <br />

After updating the regex here is the result: <br />
<img width="341" alt="style-highlights" src="https://user-images.githubusercontent.com/15775323/51901512-25676b00-23b8-11e9-9727-db23621e3c3f.png">

Now we have the highlights of the css code also in the `mj-style` tag, if for want it can make sense it would be to open a PR about it.

Thank you.

**Comment by iRyusa** [comment]
That would be a great addition ! You should open a PR imo 👍

**Comment by matteobertoldo** [comment]
@iRyusa I opened a PR a few hours ago. You can also check the code. Thanks.

**Comment by iRyusa** [comment]
I've published the new version with your changes @matteobertoldo ! Sorry about the delay, I had some issues to publish the atom package :(
