### ISSUE TITLE
MJML Atom - Update

### ISSUE THREAD

**Issue by vnunezbizcor** [mjmlio/language-mjml#20]
Would it be possible to update this package? The last update I see here was on Mar 27, 2018, and I use Atom heavily and I am so used to it.

![image](https://user-images.githubusercontent.com/54678238/63954372-dd84f100-ca37-11e9-9ce7-46c45397630e.png)

**Comment by ngarnier** [comment]
hey @vnunezbizcor, can you be a bit more specific about what updates are needed / what's missing. Would be super helpful to quickly make the needed changes :-).

**Comment by vnunezbizcor** [comment]
When updates are made to MJML, are they automatically updated on the Atom MJML package? I guess thats a better question

**Comment by ngarnier** [comment]
The Atom package simply provides shortcuts/snippets for the MJML tags, so apart if a new component is introduced there's no need to update the Atom package.
