### ISSUE TITLE
feat: remove snippets on embedded contexts

### ISSUE THREAD

**Issue by matteobertoldo** [mjmlio/language-mjml#22]
Hi @iRyusa @ngarnier! you can check the [PR](https://github.com/mjmlio/language-mjml/pulls) I sent you 2 months ago again.
In my opinion it is a very important point to be able to support Atom `Autocomplete+` in the future and therefore to be able to define the autocomplete of their attributes for each tag...something that no editor can currently provide for MJML (not even VSCode).

Thanks for your patience and I await an answer.

**Comment by ngarnier** [comment]
Sorry we didn't see the PR, we don't monitor this repo closely as there's not much activity on it. We'll review, feel free to ping us on the PR instead of creating another issue 👍
