### ISSUE TITLE
Why autocompletion would be amazing ? 

### ISSUE THREAD

**Issue by arthurkatz** [mjmlio/language-mjml#4]
Hello all, 

I think adding an autocompletion feature could be really cool. By autocompletion, I mean this atom package could suggest attributes for every components with or without default value. 
We would code even faster our emails ! Amazing right ? 

Is this feature on your roadmap ? 
If no, who is willing to help me on this ?

**Comment by ngarnier** [comment]
Hey @arthurkatz, 

I like the idea! So to make sure I understand correctly, when using `mj-text` for example, the tags generated would have all the attributes that are possible to use with it with default values and you would just have to replace them?

**Comment by arthurkatz** [comment]
Hey @ngarnier, 
I already did that for myself, I can push it for every one if you want. 
Actually if I type "text-", hit tab then it will expand to : 
`<mj-text color="#000000" font-family="Ubuntu, Helvetica, Arial, sans-serif" font-size="13px" font-style="" font-weight="" line-height="22px" text-decoration="" text-transform="" align="left" container-background-color="" padding="10px 25px"></mj-text>`

But what I was thinking about is you type "text" then expand hitting tab, you go inside the bracket hit something like "ctrl+space" and a dropdown would appear with all the attributes availables.

**Comment by ngarnier** [comment]
Thanks, I think the 2nd option is more suitable because expanding all the attributes with default values will be a problem for people using `mj-attributes` (`mj-all`, `mj-class`...) as it will override what they specified.

**Comment by arthurkatz** [comment]
Didn't thought about that ! 
I'll start working on the second option and keep you updated ;)

**Comment by barrars** [comment]
Would something like [atom/autocomplete-html](https://github.com/atom/autocomplete-html/blob/master/completions.json) work?

I love the functionality. 

Also, getting greedy here but is it be possible to have a beautify button like in the [online MJML editor](https://mjml.io/try-it-live).

**Comment by ngarnier** [comment]
I'm closing as this issue has been open for a long time, but feel free to submit a PR, it would be a great addition.
