### ISSUE TITLE
Feature request - preview html/rendered email

### ISSUE THREAD

**Issue by octoberclub** [mjmlio/language-mjml#8]
Enhance the addin to provide a preview of the changes to the transpiled html in the same way you can with some other languages such as .html, .md, and with the .rst plugin.

![atom-markdown-perview](https://cloud.githubusercontent.com/assets/509737/19439957/f66a528a-9477-11e6-9947-3b3fa7cfcb21.png)

**Comment by iRyusa** [comment]
Hi there,

I think it should have its own package, but I like the idea, I think we can fork this https://atom.io/packages/atom-html-preview

**Comment by octoberclub** [comment]
Thanks, didn't notice that plugin was available. I imagine it would work the same but with a pre-transpile step?

**Comment by iRyusa** [comment]
Exactly !

**Comment by ngarnier** [comment]
Hey @octoberclub, I have a good news, your wish was fullfilled by @iRyusa! This plugin is available here: https://atom.io/packages/mjml-preview

Cheers
